import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import Image from 'next/image'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const menuItems = [
  {
    label: 'Home',
    route: '/',
  },
  {
    label: 'Todos',
    route: '/todos',
  },
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* <Header /> */}
        <div className='min-w-dvw'>
          <div className='flex min-h-[70dvh] w-full  md:min-h-[90dvh]'>
            {children}
          </div>

          <div className='relative flex  min-h-[30dvh]  justify-between bg-secondary md:min-h-[10dvh]'>
            <Link
              href='/add-task'
              className='absolute left-1/2 top-1 inline-flex h-[64px] w-[64px] -translate-x-1/2 -translate-y-1/2 transform items-center justify-center rounded-full bg-primary'
            >
              <Image
                className='text-w flex'
                src='/images/add.png'
                alt='sort icon'
                width={24}
                height={24}
              />
            </Link>

            <div className='flex gap-10 p-4'>
              <Link href='/' className='flex flex-col items-center gap-[3px]'>
                <Image
                  className='relative h-6 w-6'
                  src='/images/home-2.png'
                  alt='sort icon'
                  width={24}
                  height={24}
                />
                <div className='flex text-xs text-white'>Home</div>
              </Link>
              <Link
                href='/calendar'
                className='flex flex-col items-center gap-[3px]'
              >
                <Image
                  className='relative h-6 w-6'
                  src='/images/calendar.png'
                  alt='sort icon'
                  width={24}
                  height={24}
                />
                <div className='flex text-xs text-white'>Calendar</div>
              </Link>
            </div>
            <div className='flex gap-10 p-4'>
              <Link href='/focus'>
                <div className='flex flex-col items-center gap-[3px]'>
                  <Image
                    className='relative h-6 w-6'
                    src='/images/clock.png'
                    alt='sort icon'
                    width={24}
                    height={24}
                  />
                  <div className='flex text-xs text-white'>Focus</div>
                </div>
              </Link>
              <div className='flex flex-col items-center gap-[3px]'>
                <Image
                  className='relative h-6 w-6'
                  src='/images/user.png'
                  alt='sort icon'
                  width={24}
                  height={24}
                />
                <div className='flex text-xs text-white'>Profile</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
